name: Build and Release tfenv

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build Windows Executable
        run: go build -o build/tfenv-windows-${{ matrix.goarch }}.exe

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/

  build-linux-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build Linux/macOS Executable
        run: go build -o build/tfenv-linux-${{ matrix.goarch }}

      - name: Upload Linux/macOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-macos-build
          path: build/

  release:
    needs: [build-windows, build-linux-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download All Built Binaries
        uses: actions/download-artifact@v3
        with:
          path: build/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files:
            - build/tfenv-windows-amd64.exe
            - build/tfenv-windows-arm64.exe
            - build/tfenv-linux-amd64
            - build/tfenv-linux-arm64
            - build/tfenv-darwin-amd64
            - build/tfenv-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
