name: Build and Release tfenv

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build CLI for Multiple Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build Executable
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/tfenv-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Remove Existing Artifact (if any)
        continue-on-error: true
        run: rm -rf build/tfenv-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfenv-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/tfenv-${{ matrix.goos }}-${{ matrix.goarch }}
